import type { Metadata } from "next";
import { getUserAction } from '@/lib/data/account/fetch';
import AuthenticationPage from '@/modules/account/templates/login/loginTemplate';
import { AuthProvider } from '@/lib/context/auth/user';
import { DrawerManagerProvider } from '@/lib/context/drawer/drawer';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let value = await getUserAction();

  if (value)
    return (
      <DrawerManagerProvider>
        {children}
      </DrawerManagerProvider>
    );
  else
    return (
      <AuthenticationPage />
    );
}
