import type { Metadata } from "next";
import { MobileNavBar, NavBar } from '@/modules/layout/components/nav';
import { getUserAction } from '@/lib/data/account/fetch';
import AuthenticationPage from '@/modules/account/templates/login/loginTemplate';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let value = await getUserAction();

  if (value)
    return (
      <div className='flex'>
        {/* <SideBarSection /> */}
        <main className='flex-1 '>
          <NavBar />
          <div className='min-h-14 h-[8vh] max-h-20' />
          {children}
        </main>
      </div>
    );
  else
    return (
      <AuthenticationPage />
    );
}
