import type { Metadata } from "next";
import { SideBarSection } from '@/modules/layout/templates/sidebar';
import { MobileNavBar, NavBar } from '@/modules/layout/templates/nav';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='flex'>
      <SideBarSection />
      <main className='flex-1 sm:ml-14'>
        <MobileNavBar />
        <NavBar />
        {children}
      </main>
    </div>
  );
}
