import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from '@/lib/context/theme';
import { AuthProvider } from '@/lib/context/auth/user';
import { Toaster } from "@/modules/ui/toaster"
import "./globals.css";
import { ProfileProvider } from '@/lib/context/account';

const inter = Inter({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <ProfileProvider>
              {children}
            </ProfileProvider>
          </AuthProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
