import { ProductsProvider } from '@/lib/context/product';
import { PurchasesProvider } from '@/lib/context/purchase';
import { ExportPurchaseProvider } from '@/lib/context/purchaseExport';
import { VendorsProvider } from '@/lib/context/vendor';
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <div>
      <ExportPurchaseProvider>
        <PurchasesProvider>
          <VendorsProvider>
            <ProductsProvider>
              {children}
            </ProductsProvider>
          </VendorsProvider>
        </PurchasesProvider>
      </ExportPurchaseProvider>
    </div>
  );
}
