import type { Metadata } from "next";
import { NavBar } from '@/modules/layout/components/nav';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='flex'>
      <main className='flex-1 '>
        <NavBar />
        <div className='min-h-14 h-[8vh] max-h-20' />
        {children}
      </main>
    </div>
  );
}
